### ISSUE TITLE
An application for automation using Jarvis

### ISSUE THREAD

**Issue by aditya172926** [divshekhar/Jarvis#3]
I have made an desktop automation script to automate repeating tasks on MacBook such as opening an Application, searching the web and more using a voice recognition commands similar to your Jarvis.

I would like to contribute it to your Jarvis, (mark 2).
Please assign this to me. @divshekhar

**Comment by divshekhar** [comment]
Thanks, @aditya172926 for showing interest in contribution. Assigning it to you.

**Comment by aditya172926** [comment]
@divshekhar please add Hacktoberfest label to this issue.
